### PR TITLE
Qa component

### PR DESCRIPTION
**Pull request by JTVong**
Hi! James

-  I made a layout for QA-section to match display requirement from DOCS
- I am still working on making Vote helpfulness, add more Question and add Answer be functional

### CODE REVIEW

**Review by one-summers-day — APPROVED** [review]
LGTM!

**Comment by JTVong** [comment]
@one-summers-day  I fixed all conflicts and added Overview component to main App

**Comment by one-summers-day** [comment]
Thanks Nat, I'll look at this now.

**Comment by one-summers-day** [comment]
@JTVong @saarikak @justinhungle this looks good, but the CIRCLECI automated suite is failing. Specifically, the >>>>HEAD appended by github is causing a syntax issue with JEST.

I'll merge this because that's a very minor issue. When I make my pull request I'll also include an example test and fix the JEST test that's broken. 

Overall amazing work.

**Pull request merged**
